# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 03:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Nome')),
                ('logo', models.ImageField(upload_to=b'', verbose_name=b'Logo')),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competi\xe7\xe3o',
                'verbose_name_plural': 'Competi\xe7\xf5es',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Nome')),
                ('result_home', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Resultado Mandante')),
                ('result_visitor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Resultado Visitante')),
                ('local', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Local')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name=b'Data e Hora')),
            ],
            options={
                'verbose_name': 'Competi\xe7\xe3o',
                'verbose_name_plural': 'Competi\xe7\xf5es',
            },
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition')),
            ],
            options={
                'verbose_name': 'Rodada',
                'verbose_name_plural': 'Rodadas',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Nome')),
                ('flag', models.ImageField(upload_to=b'', verbose_name=b'Escudo')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='rounds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Rounds'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mandante', to='core.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visitante', to='core.Team'),
        ),
    ]
