# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionHasTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team')),
            ],
            options={
                'verbose_name': 'Time/competi\xe7\xe3o',
                'verbose_name_plural': 'Times/competi\xe7\xf5es',
            },
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.AddField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(through='core.CompetitionHasTeam', to='core.Team'),
        ),
    ]
